name: Log on fork
on:
    fork:
jobs:
    Create-log-file:
        runs-on: ubuntu-latest
        steps:
            - name: Create log file
              run: echo "${{ toJson(github.event.forkee) }} forked the repo - $(date)" > log.txt
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: fork_log
                path: log.txt