name: Log on fork
on:
    push:
jobs:
    Create-log-file:
        runs-on: ubuntu-latest
        steps:
            - name: Create log file
              run: echo "Someone forked the repo - $(date)" > log.md
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: fork_log
                path: log.md