name: Run express server
on: 
  push:
    branches: 
      - main
    paths: 
      - '**.js'
jobs:
    Get-code-and-run:
        environment: Development
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Get code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Run server
              env:
                PORT: ${{ vars.PORT }}
              run: node index.js
              